head(gdp)
require(reshape2)
gdpCast <- dcast(Year ~ Country, data=gdp[, c("Country", "Year", "PerCapGDP")],
                 value.var="PerCapGDP")
head(gdpCast)
gdpTS <- ts(data=gdpCast[, -1], start=min(gdpCast$Year), end=max(gdpCast$Year))
plot(gdpTS, plot.type = "single", col=1:8)
legend("topleft", legend = colnames(gdpTS), ncol = 2, lty = 1, col = 1:8, cex = .9)
numDiffs <- ndiffs(gdpTS)
numDiffs
gdpDiffed <- diff(gdpTS, differences = numDiffs)
plot(gdpDiffed, plot.type = "single", col = 1:7)
install.packages("vars")
require(vars)
gdpVar <- VAR(gdpDiffed, lag.max = 12)
gdpVar$p
names(gdpVar$varresult)
class(gdpVar$varresult$Canada)
head(gdpVar$varresult$Canada)
head(coef(gdpVar$varresult$Canada),10)
require(coefplot)
coefplot(gdpVar$varresult$Canada)
coefplot(gdpVar$varresult$Japan)
predict(gdpVar, n.ahead = 5)
